# docker-compose.yml
version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      FRONTEND_DOMAIN: http://localhost:8081  # 限制仅允许前端域名跨域
      API_BASE_PATH: ""                       # API 路径前缀设为空
      BIND_ADDRESS: 0.0.0.0
      PORT: 80
    expose:
      - 80
    networks:
      - speedtest-net

networks:
  speedtest-net:
    driver: bridge
